# Generated by Django 3.1.4 on 2021-08-26 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Inventory owner',
                'verbose_name_plural': 'Inventory owners',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('ean', models.CharField(blank=True, db_index=True, max_length=13, null=True, verbose_name='EAN')),
                ('unit', models.CharField(default='unit', max_length=20, verbose_name='Measurement Unit')),
                ('autosync', models.BooleanField(default=True, verbose_name='Autosync')),
            ],
            options={
                'verbose_name': 'Canonical product',
                'verbose_name_plural': 'Canonical products',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('ean', models.CharField(blank=True, db_index=True, max_length=13, null=True, verbose_name='EAN')),
                ('unit', models.CharField(default='unit', max_length=20, verbose_name='Measurement Unit')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Sku')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='inventory.inventoryowner')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Inventory item',
                'verbose_name_plural': 'Inventory items',
                'unique_together': {('owner', 'product'), ('owner', 'ean'), ('owner', 'sku')},
            },
        ),
        migrations.RunSQL(
            sql='ALTER SEQUENCE inventory_product_id_seq RESTART WITH 10000000;',
        ),
    ]
